### PR TITLE
Fix wrong completion of comments

### LINKED ISSUE #52: Error: "Cannot read property 'loc' of undefined"
# Minimum operation for the error

```bash
mkdir -p /tmp/err_sample
cd  /tmp/err_sample
npm install textlint textlint-plugin-latex2e textlint-rule-no-nfd
echo '{"plugins":["latex2e"],"rules":{"no-nfd":true}}' > .textlintrc
echo -e 'A%B\nC' > sample.tex
npx textlint ./sample.tex
```

No error with the following setting.

```bash
echo '{"rules":{"no-nfd":true}}' > .textlintrc
npx textlint ./sample.tex
```
Here is [package-lock.json](https://github.com/textlint/textlint-plugin-latex2e/files/5746541/package-lock.json.txt).

# Error message

```txt
✖ Error
Cannot read property 'loc' of undefined

✖ Stack trace
TypeError: Cannot read property 'loc' of undefined
    at validate (/private/tmp/err_sample/node_modules/@textlint/kernel/lib/context/TextlintSourceCodeImpl.js:37:14)
    at new TextlintSourceCodeImpl (/private/tmp/err_sample/node_modules/@textlint/kernel/lib/context/TextlintSourceCodeImpl.js:56:9)
    at TextlintKernel._parallelProcess (/private/tmp/err_sample/node_modules/@textlint/kernel/lib/textlint-kernel.js:153:26)
    at /private/tmp/err_sample/node_modules/@textlint/kernel/lib/textlint-kernel.js:100:26
npm ERR! code 1
npm ERR! path /private/tmp/err_sample
npm ERR! command failed
npm ERR! command sh -c textlint ./sample.tex
```

# Environment

```console
$  npm list
err_sample@ /private/tmp/err_sample
├── textlint-plugin-latex2e@1.0.4
├── textlint-rule-no-nfd@1.0.2
└── textlint@11.7.7
```

### PR DESCRIPTION
**Pull request by pddg**
fix #52 

Fix to use `range` instead of `loc` to check the location of the node in the AST.

### CODE REVIEW

File: src/completeComment.ts [hunk 1]
```diff
@@ -56,35 +56,17 @@ export const convertCommentToTxtNode = (
 };
 
 export const isAppearedBeforeNode = (
-  nodeLocation: TxtNodeLineLocation,
-  commentLocation: TxtNodeLineLocation
+  nodeRange: TextNodeRange,
+  commentRange: TextNodeRange
```
Comment (tani) [inline src/completeComment.ts:60]: What is it difference between `TxtNodeLineLocation` and `TextNodeRange`?
Please tell me why this change solved the issue? Thanks.

Comment (pddg) [reply src/completeComment.ts:60]: While debugging, I found that when parsing the sample in the issue, the comment was inserted in an unexpected place. This seemed to have introduced a node with an invalid location into the AST.

<details><summary>Generated AST in master branch (Inserted comment has invalid location)</summary>

```js
      {
        type: 'Document',
        raw: 'A%B\nC',
        range: [ 0, 5 ],
        loc: { start: { line: 1, column: 0 }, end: { line: 2, column: 0 } },
        children: [
          {
            loc: { start: { line: 1, column: 0 }, end: { line: 2, column: 1 } },
            range: [ 0, 5 ],
            raw: 'A%B\nC',
            type: 'Paragraph',
            children: [
              {
                loc: {
                  start: { line: 1, column: 0 },
                  end: { line: 1, column: 1 }
                },
                range: [ 0, 1 ],
                raw: 'A',
                type: 'Str',
                value: 'A'
              },
              {
                loc: {
                  start: { line: 1, column: 1 },
                  end: { line: 2, column: 0 }
                },
                range: [ 1, 4 ],
                raw: '%B\n',
                type: 'Html',
                value: '%B\n'
              },
              {
                loc: {
                  start: { line: 2, column: 0 },
                  end: { line: 2, column: 1 }
                },
                range: [ 4, 5 ],
                raw: 'C',
                type: 'Str',
                value: 'C'
              }
            ]
          },
          {
            loc: { start: { line: 2, column: 1 }, end: { line: 1, column: 1 } },
            range: [ 5, 1 ],
            raw: '',
            type: 'Html',
            value: ''
          },
          {
            loc: { start: { line: 1, column: 1 }, end: { line: 2, column: 0 } },
            range: [ 1, 4 ],
            raw: '%B\n',
            value: 'B',
            type: 'Comment'
          }
        ]
      }
```

</details>

I found that this might be caused by the wrong algorithm of `insertComment`. When I thought about it, I realized that the algorithm would be simpler if I used range rather than location. After this change, the generated AST becomes valid.

<details><summary>Generated AST in this branch</summary>

```js
      {
        type: 'Document',
        raw: 'A%B\nC',
        range: [ 0, 5 ],
        loc: { start: { line: 1, column: 0 }, end: { line: 2, column: 0 } },
        children: [
          {
            loc: { start: { line: 1, column: 0 }, end: { line: 2, column: 1 } },
            range: [ 0, 5 ],
            raw: 'A%B\nC',
            type: 'Paragraph',
            children: [
              {
                loc: {
                  start: { line: 1, column: 0 },
                  end: { line: 1, column: 1 }
                },
                range: [ 0, 1 ],
                raw: 'A',
                type: 'Str',
                value: 'A'
              },
              {
                loc: {
                  start: { line: 1, column: 1 },
                  end: { line: 2, column: 0 }
                },
                range: [ 1, 4 ],
                raw: '%B\n',
                value: 'B',
                type: 'Comment'
              },
              {
                loc: {
                  start: { line: 2, column: 0 },
                  end: { line: 2, column: 1 }
                },
                range: [ 4, 5 ],
                raw: 'C',
                type: 'Str',
                value: 'C'
              }
            ]
          }
        ]
      }
```

</details>

I use `npm link` and test sample TeX source. textlint does not show any error.

Comment (tani) [reply src/completeComment.ts:60]: Hmm, you mean that this pr changes the algorithm to be work expectedly with TextNodeRange, right? If so, I need to review more carefully. If it is just minor (or trivial) changes, I can approve immediately.

Comment (pddg) [reply src/completeComment.ts:60]: It seems that the previous implementation was complicated and contained bugs. I consider this to be just a bug fix, not a major algorithm change :) (In fact, the unit tests from before are working fine without any changes.)

**Comment by pddg** [comment]
@tani It looks like I accidentally dropped some test cases. I will fix it.

File: src/completeComment.ts [hunk 2]
```diff
@@ -56,35 +56,17 @@ export const convertCommentToTxtNode = (
...
-    nodeLocation.end.line >= commentLocation.end.line
-  ) {
-    // \begin{document}\end{document} % comment
-    if (nodeLocation.end.line === commentLocation.end.line) {
-      return nodeLocation.end.column > commentLocation.start.column;
-    }
-    return true;
-  }
-  return false;
+  return nodeRange[0] <= commentRange[0] && nodeRange[1] >= commentRange[1]
```
Comment (tani) [inline src/completeComment.ts:69]: Is this change the most essential changes in this request?

Comment (pddg) [reply src/completeComment.ts:69]: Yes. The previous implementation may cause a bug if a node comes immediately after other node. Those `column` values overlap, but that was not taken into account, I think.

Comment (pddg) [reply src/completeComment.ts:69]: It is possible that simply changing `nodeLocation.end.column > commentLocation.start.column` to `nodeLocation.end.column >= commentLocation.start.column` will solve the problem, but it is simpler to implement with TxtNodeRange than to think about this complex implementation.

Comment (tani) [reply src/completeComment.ts:69]: Thank you for the kind comment. I catch the meaning perfectly. I will merge after adding test cases.

**Comment by tani** [comment]
Cheers! :beers:
